import type { CraftInput } from './types';

export const ALBION_PRESETS: Record<string, Omit<CraftInput, 'returnRate' | 'taxPercentage' | 'marketValue'>> = {
//   'Wood Planks': {
//     itemName: 'Wood Planks',
//     material1: { name: 'Wood', silverValue: 1.5 },
//     material2: { name: 'Water', silverValue: 2 },
//     material1Needed: 8,
//     material2Needed: 4,
//     artifacts: [],
//     artifactQuantity: 0,
//   },
//   'Iron Bars': {
//     itemName: 'Iron Bars',
//     material1: { name: 'Iron Ore', silverValue: 3.5 },
//     material2: { name: 'Coal', silverValue: 2.5 },
//     material1Needed: 8,
//     material2Needed: 4,
//     artifacts: [],
//     artifactQuantity: 0,
//   },
//   'Steel Bars': {
//     itemName: 'Steel Bars',
//     material1: { name: 'Iron Bars', silverValue: 50 },
//     material2: { name: 'Coal', silverValue: 2.5 },
//     material1Needed: 4,
//     material2Needed: 2,
//     artifacts: [],
//     artifactQuantity: 0,
//   },
//   'Hardened Leather': {
//     itemName: 'Hardened Leather',
//     material1: { name: 'Leather', silverValue: 5 },
//     material2: { name: 'Resin', silverValue: 4 },
//     material1Needed: 8,
//     material2Needed: 4,
//     artifacts: [],
//     artifactQuantity: 0,
//   },
//   'Cloth': {
//     itemName: 'Cloth',
//     material1: { name: 'Fiber', silverValue: 2 },
//     material2: { name: 'Water', silverValue: 2 },
//     material1Needed: 8,
//     material2Needed: 4,
//     artifacts: [],
//     artifactQuantity: 0,
//   },
//   'Ancient Rune': {
//     itemName: 'Ancient Rune',
//     material1: { name: 'Rune Essence', silverValue: 100 },
//     material2: { name: 'Dust', silverValue: 30 },
//     material1Needed: 4,
//     material2Needed: 8,
//     artifacts: [{ name: 'Rune Artifact', silverValue: 500 }],
//     artifactQuantity: 1,
//   },
//   'Glowing Shard': {
//     itemName: 'Glowing Shard',
//     material1: { name: 'Crystal', silverValue: 60 },
//     material2: { name: 'Essence', silverValue: 80 },
//     material1Needed: 4,
//     material2Needed: 2,
//     artifacts: [{ name: 'Shard Artifact', silverValue: 400 }],
//     artifactQuantity: 1,
//   },
//   'Copper Ore': {
//     itemName: 'Copper Ore',
//     material1: { name: 'Ore Fragment', silverValue: 1.2 },
//     material2: { name: 'Stone', silverValue: 0.8 },
//     material1Needed: 10,
//     material2Needed: 5,
//     artifacts: [],
//     artifactQuantity: 0,
//   },
//   'Silver Ore': {
//     itemName: 'Silver Ore',
//     material1: { name: 'Ore Fragment', silverValue: 1.2 },
//     material2: { name: 'Stone', silverValue: 0.8 },
//     material1Needed: 12,
//     material2Needed: 6,
//     artifacts: [],
//     artifactQuantity: 0,
//   },
//   'Gold Ore': {
//     itemName: 'Gold Ore',
//     material1: { name: 'Ore Fragment', silverValue: 1.2 },
//     material2: { name: 'Stone', silverValue: 0.8 },
//     material1Needed: 16,
//     material2Needed: 8,
//     artifacts: [],
//     artifactQuantity: 0,
//   },
};
